"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Search, Filter, ShieldCheck, MapPin } from "lucide-react";

const danGrades = [
  "Shodan (1. Dan)", "Nidan (2. Dan)", "Sandan (3. Dan)", 
  "Yondan (4. Dan)", "Godan (5. Dan)", "Rokudan (6. Dan)", 
  "Nanadan (7. Dan)", "Hachidan (8. Dan)", "Kudan (9. Dan)"
];

const registryData = [
  // --- SHODAN (1. DAN) ---
  { lastName: "Abelido", firstName: "Benjamin", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Abelido", firstName: "Billy", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Abelido", firstName: "Carl", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Abion", firstName: "Julius", dojo: "S.K.I.F. - New Jersey", rank: "Shodan (1. Dan)" },
  { lastName: "Akbar", firstName: "Mark", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Alarcon", firstName: "Kyra", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Aliva", firstName: "Erica", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Almendarez", firstName: "Jesus", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Almonte", firstName: "Kevin", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Altos", firstName: "Marc", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Anderson", firstName: "Shaun", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Andrian", firstName: "Nabil", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ansari", firstName: "Sohail", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Arias", firstName: "Pablo", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Armao Peng", firstName: "Linda", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Armitage", firstName: "Graham", dojo: "Rochester Shotokan Karate Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Armstrong", firstName: "Joseph", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Arndt", firstName: "Kraig", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Arndt", firstName: "Kyle", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Arsanjani", firstName: "Sam", dojo: "Shotokan Karate Keiko Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Avila", firstName: "Erika", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Awwad", firstName: "Abdou", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Azada", firstName: "Catherine", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Babani", firstName: "Bridget", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Baghirov", firstName: "Eldar", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Bah", firstName: "Yves Stephane", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Barahona", firstName: "Dylan", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Barahona", firstName: "Michael", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Barbecho", firstName: "Jose", dojo: "D-Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Barnabei", firstName: "Massimo", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Barrera", firstName: "Alejandro", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Barrera", firstName: "Luis", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Bateman", firstName: "Thomas", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Bateman", firstName: "Jonathan", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Bazantes", firstName: "Miguel", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Beal", firstName: "Nathaniel", dojo: "Maine Shotokan Karate Association", rank: "Shodan (1. Dan)" },
  { lastName: "Benhabib", firstName: "Natalie", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Benoit", firstName: "Fabrice", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Bhattacharya", firstName: "Srimoyee", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Bickham", firstName: "April", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Bird", firstName: "Peter Anthony", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Bishop", firstName: "Peter", dojo: "New England Shotokan Karate-Do", rank: "Shodan (1. Dan)" },
  { lastName: "Blackman", firstName: "Carlton", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Blanchard", firstName: "Keith", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Blanchard", firstName: "Shannon", dojo: "Rochester Shotokan Karate Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Bonell", firstName: "Sandra", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Booker", firstName: "Imani N.", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Booker Jr.", firstName: "Diamond T.", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Boyd", firstName: "Alex", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Brand", firstName: "William", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Breed", firstName: "Nicholas", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Breines", firstName: "Ron", dojo: "Jemes Valley Martial Arts", rank: "Shodan (1. Dan)" },
  { lastName: "Brickham", firstName: "Charles", dojo: "SKIF of Maine – Millinocket", rank: "Shodan (1. Dan)" },
  { lastName: "Bui", firstName: "Khanh", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Burke", firstName: "Chris", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Burruso", firstName: "Joseph", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Cadena", firstName: "Alexandra", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Calloway", firstName: "Dennis", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Cambia", firstName: "Princeton", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Canaan", firstName: "Mark", dojo: "Way of Japan", rank: "Shodan (1. Dan)" },
  { lastName: "Carroll", firstName: "Tatiana", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Carroll Jr.", firstName: "Travis", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Castillo", firstName: "Jesse", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Castillo", firstName: "Kassandra", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Cathey", firstName: "Ron", dojo: "RGV Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Cattapan", firstName: "Andrew", dojo: "American Tiger Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Ceglio", firstName: "Michael", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Chamberlain", firstName: "Benjamin", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Chang", firstName: "Airi", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Cheng", firstName: "Francis", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Shodan (1. Dan)" },
  { lastName: "Chibundu Jr", firstName: "Emmanuel", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Chirhart", firstName: "Ben", dojo: "Peak Performance Shotokan Karate-Do", rank: "Shodan (1. Dan)" },
  { lastName: "Chong", firstName: "Chesten", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Cisnero", firstName: "Jorge", dojo: "Texas A & M Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Cocucci", firstName: "Franco", dojo: "Shotokan-Ryu Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Concepcion", firstName: "Edwin", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Consuegra", firstName: "Luis", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Correia Da Silva", firstName: "Sophia", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Cortez", firstName: "Ana", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Creznic", firstName: "Alex", dojo: "Maine Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Cruz", firstName: "Justin", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Cuizon", firstName: "Morgan", dojo: "Kaumakapili Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Dabbs", firstName: "Meric", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Daher", firstName: "Kathryn", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Daly", firstName: "Brian", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Dandenaeau", firstName: "Bryan", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Davidson", firstName: "Richard", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Davis", firstName: "Fred S", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "DeLaCruz", firstName: "L Felipe", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Delelis", firstName: "Marc", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Delewis", firstName: "Pierre", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Dell’Aquila", firstName: "Alyssa", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Den Uijl", firstName: "Christina", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Deschapelles", firstName: "Edwardo", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Doeur", firstName: "Nathalie", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Domingo", firstName: "Antonio", dojo: "I.K.I.", rank: "Shodan (1. Dan)" },
  { lastName: "Donovan", firstName: "Mark", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Doyle", firstName: "Shawn A.", dojo: "SKIF of Maine – Millinocket", rank: "Shodan (1. Dan)" },
  { lastName: "Drew", firstName: "Brad", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Duarte", firstName: "Robert", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Duffy", firstName: "Kevin", dojo: "Shotokan-Ryu Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Dumortier", firstName: "Simon", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Duya", firstName: "Matthew", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Dwik", firstName: "Maher", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Edstrom", firstName: "Aaron", dojo: "S.K.I.F. - Hawaii - Waikoloa", rank: "Shodan (1. Dan)" },
  { lastName: "Eguiluz", firstName: "Manuel", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ehrenreich", firstName: "Eric", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ellinikos", firstName: "Natalia", dojo: "S.K.I.F. - New York", rank: "Shodan (1. Dan)" },
  { lastName: "Faridi", firstName: "Tooraj", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Fernandez", firstName: "Alessandra", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Fernandez", firstName: "Joshua", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Fernandez", firstName: "Marco", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ferrando", firstName: "Matthew", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Fichter", firstName: "Joseph", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Fisher", firstName: "Sara", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Flatoff", firstName: "Janice", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Fleming", firstName: "Diana", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Fong", firstName: "Ken Eu", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Fong", firstName: "Wesley K. L.", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Shodan (1. Dan)" },
  { lastName: "Fonseca Born", firstName: "Eduardo", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Ford", firstName: "Antoine", dojo: "S.K.I.F. - New Jersey", rank: "Shodan (1. Dan)" },
  { lastName: "Frick", firstName: "Juergen", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Friel", firstName: "Cynthia", dojo: "SKIF of Maine – Millinocket", rank: "Shodan (1. Dan)" },
  { lastName: "Frikman", firstName: "Solomon", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Frost", firstName: "Duncan", dojo: "New England Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Fuenmayor", firstName: "Ernesto", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Galego", firstName: "Joshep", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Gandhi", firstName: "Paras", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ganesh", firstName: "Haran", dojo: "Katy/Richmond Karate-dō", rank: "Shodan (1. Dan)" },
  { lastName: "Garcia", firstName: "Jose", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Garza", firstName: "David", dojo: "RGV Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Gaulin", firstName: "Trisha", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Gavira", firstName: "Alejandro", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Gaw", firstName: "Jonathan", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Geiger", firstName: "Cameron", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Gilbert", firstName: "William", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "Ginter", firstName: "Emily", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Glenn", firstName: "Norm", dojo: "Shotokan Karate Keiko Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Glover", firstName: "Chelsea", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Goller", firstName: "William", dojo: "Maine Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Gopinath", firstName: "Raghav", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Gopinath", firstName: "Gandhi", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Grazhdonskaya", firstName: "Olga", dojo: "S.K.I.F. - New York", rank: "Shodan (1. Dan)" },
  { lastName: "Guanson", firstName: "Ha’aheo", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Guzan", firstName: "Kimberly", dojo: "New England Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ha", firstName: "Rachel", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Habib", firstName: "Samer", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Haddad", firstName: "John", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Hammond", firstName: "Ledia", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Handman", firstName: "Jacob", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Helduser", firstName: "Matthias", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Henri", firstName: "Carl", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Hernaez", firstName: "Ana", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Hernaez", firstName: "Mathew", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Hernandez", firstName: "Roberto", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Hernandez", firstName: "Emilio", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Hinojosa", firstName: "Heath", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Hiyoshi", firstName: "Haruka", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Hoang", firstName: "Ngamy", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Horn", firstName: "Andrew", dojo: "RGV Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Howard", firstName: "Alexandra", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Hubert", firstName: "Savana", dojo: "Golden Tiger Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Hutnik", firstName: "Markus", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Hutnik", firstName: "Nate", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ingerson", firstName: "Marc", dojo: "SKIF of Maine – Millinocket", rank: "Shodan (1. Dan)" },
  { lastName: "Iobst", firstName: "Christopher", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Iobst", firstName: "Nina", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Ishida", firstName: "Terrence", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Ishii", firstName: "Rebeca", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Jain", firstName: "Pryia", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Jarrar", firstName: "Aktham (AJ)", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Jennison", firstName: "Cameron", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Jimenez", firstName: "Brandon", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Jimenez", firstName: "Jorge", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Jimenez", firstName: "Natvidad", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Johnson", firstName: "Robin", dojo: "ShoShin Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Kaminsky", firstName: "Ellen", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kaneko", firstName: "Matthew", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Karthik", firstName: "Vrushab", dojo: "Hillsboro Shotokan Karate Club", rank: "Shodan (1. Dan)" },
  { lastName: "Keeney", firstName: "Jackson", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kerestes", firstName: "Rebecca", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Khosravi", firstName: "Shahzad", dojo: "Hillsboro Shotokan Karate Club", rank: "Shodan (1. Dan)" },
  { lastName: "Kink", firstName: "John", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kirby", firstName: "James", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kiyuna", firstName: "Deneen", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Klein", firstName: "Kathy", dojo: "SKIF of Maine – Millinocket", rank: "Shodan (1. Dan)" },
  { lastName: "Klotz", firstName: "Andrew Criston", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Knapp", firstName: "Ted", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Knowlton", firstName: "Emma", dojo: "Golden Tiger Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kolachina", firstName: "Ravi", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Kopacz", firstName: "Tyler", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kosinski", firstName: "Mark", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Kriete", firstName: "Eric", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Krommueller", firstName: "David", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Kulasekara", firstName: "Michaela", dojo: "Golden Tiger Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lacar", firstName: "TR Jr", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Ladisa", firstName: "Justine", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "LaFleur", firstName: "Jacki", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "LaFleur", firstName: "Randi", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lapiana", firstName: "Christopher", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lau", firstName: "Frank", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Lawrence", firstName: "Aldwyn", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lawrence", firstName: "Eric", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Legere", firstName: "Frederick", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Leggett", firstName: "Carl", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "LeVigne", firstName: "Joe", dojo: "Maine Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Levy", firstName: "Peter", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Levy", firstName: "Spencer", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Libby", firstName: "Hunter", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Locaile", firstName: "Carlos", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Loetzerich", firstName: "Karl", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Loetzerich", firstName: "Ronda", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Loveje", firstName: "Klevin", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lua", firstName: "Felipe", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lucar", firstName: "TR JR", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Lucca", firstName: "Robert", dojo: "Shotokan-Ryu Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Lum", firstName: "Michael", dojo: "JCCH", rank: "Shodan (1. Dan)" },
  { lastName: "Lyons", firstName: "David", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Lytz", firstName: "Walt", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "MacDonald", firstName: "Abigail", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Macedo", firstName: "Christopher", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Maddux", firstName: "Daniel", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Madia", firstName: "Richard", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Magdaleno", firstName: "Madeleine", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Magdaleno", firstName: "Maite", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Magday", firstName: "Marcicel", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Mangaoang", firstName: "Rizalino", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Shodan (1. Dan)" },
  { lastName: "Mansfield", firstName: "John", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Mansyur", firstName: "Julian", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Marks", firstName: "Henry", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Marques", firstName: "Donald", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Marquez", firstName: "Ceclia", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Marshik", firstName: "Allana", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Martins Cruz", firstName: "Dae Jung", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Massimo", firstName: "Massimo", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Matsuoka", firstName: "Corey", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Shodan (1. Dan)" },
  { lastName: "Mayschak", firstName: "Aedan", dojo: "American Tiger Karate", rank: "Shodan (1. Dan)" },
  { lastName: "McCue", firstName: "Carlos", dojo: "SKIF of Maine", rank: "Shodan (1. Dan)" },
  { lastName: "McCurrach", firstName: "Lee", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "McDermott", firstName: "Caitlin", dojo: "RGV Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "McFall", firstName: "Tetsuo", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "McGovney", firstName: "James", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "McQueen", firstName: "Sheila", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Medrano", firstName: "Joseph", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Mendoza", firstName: "Daniel", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Meniri", firstName: "Khalid", dojo: "S.K.I.F. - New York", rank: "Shodan (1. Dan)" },
  { lastName: "Menocal", firstName: "Laura", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Mercado Jr.", firstName: "Angel", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Mercieca", firstName: "Christina", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Metcalf", firstName: "Addison", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Meza", firstName: "Guillermo", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Milanes", firstName: "Justin", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Miles", firstName: "Robert", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Millan", firstName: "Jorge", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Miller", firstName: "Ariel", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Mittal", firstName: "Pallavi", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Moeller", firstName: "Mark", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Montalvo", firstName: "Miguel", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Moreno", firstName: "Victor", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Morita", firstName: "Mark", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Muniz", firstName: "Henry", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Munoz", firstName: "Henry", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Munroe", firstName: "Josiah Antwan", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Murawaski", firstName: "Robert", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Mwara", firstName: "Kamwana", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Nair", firstName: "Babu", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Nakanishi", firstName: "Paul", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Namba", firstName: "Tetsuya", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Naravane", firstName: "Ameay", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Naravane", firstName: "Aniket", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Navarrete", firstName: "Genesis", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Navarro", firstName: "Luis", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ndem", firstName: "Alexandra", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Nguyen", firstName: "Thuc", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Nilson", firstName: "April", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Nilson", firstName: "Michelle", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Noddin", firstName: "Christopher", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Norder", firstName: "Jim", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "O’Brien", firstName: "Randy", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Odani", firstName: "Nick", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Olaf", firstName: "Michael", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ono", firstName: "Norimuchi", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ono", firstName: "Yoshiyuho", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ordonez", firstName: "Adrian", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Ordonez", firstName: "Mario", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Oritz", firstName: "Erik", dojo: "American Tiger Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ortiz", firstName: "Mana", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Oshiro", firstName: "Wyatt", dojo: "JCCH", rank: "Shodan (1. Dan)" },
  { lastName: "Oshiro", firstName: "Andrew", dojo: "JCCH", rank: "Shodan (1. Dan)" },
  { lastName: "Ouimette", firstName: "Angela", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Oxley", firstName: "Benjamin", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Oxley", firstName: "Gregory", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Ozawa", firstName: "Gary", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Pangilinan", firstName: "Miguel", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Parin", firstName: "John Vincent", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Patel", firstName: "Sonia", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Patterson", firstName: "Daniel", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Paulson", firstName: "Faye", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Pautz", firstName: "Matthew", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Pavealksi", firstName: "Lee", dojo: "YMCA Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Peralta", firstName: "Jimena", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Perez", firstName: "Jonine", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Perez", firstName: "Juan", dojo: "SKI Florida", rank: "Shodan (1. Dan)" },
  { lastName: "Perez-Lopez", firstName: "Jorge", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Picart", firstName: "Dylan", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Pinzon", firstName: "Luis", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Plotke", firstName: "Robert", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Plume", firstName: "Isabel", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Pope", firstName: "Colin", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Pope", firstName: "Hans", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Poussard", firstName: "Kevin", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Prasad", firstName: "Prabhakar", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ramaker", firstName: "Brent", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Ramic", firstName: "Elvis", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Ramic", firstName: "Sabina", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Ramon", firstName: "Guillermo", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Reggeti", firstName: "Ivan", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Relacion", firstName: "Jonathan", dojo: "Kauai Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Reyes", firstName: "Antonella", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Ribando", firstName: "John Anthony", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rivero", firstName: "Angelica", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Rivero", firstName: "Jaime", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Rmiochu", firstName: "Rab", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Rocco", firstName: "Christopher", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Rocha", firstName: "Samantha", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rodriguez", firstName: "Mathias", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Rodriquez", firstName: "Kevin", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Roerden", firstName: "Michaela", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rogowski", firstName: "Michael", dojo: "American Tiger Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Rosario", firstName: "Ana", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rosenberg", firstName: "Jill L.", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rossi Jr.", firstName: "Fred", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Rowner", firstName: "Eric", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Roxburgh-Edstrom", firstName: "Heidi", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Rugama", firstName: "Zael", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Ruiz", firstName: "Edward", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Ruttimann", firstName: "Marco", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Ruttmann", firstName: "Alejandra", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Salman", firstName: "Joshua", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Salman", firstName: "Luke Jennings", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Salman", firstName: "Jake Davis", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Samah", firstName: "Ali", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sampson", firstName: "Rachel", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Sanchez Hernande", firstName: "Joaquin", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Sanchis Sr.", firstName: "John", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Santiago", firstName: "Ulloa", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Santori", firstName: "Gina", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "Saputo", firstName: "Michael", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sardesai", firstName: "Amol", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Sato", firstName: "Dayton", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Sato", firstName: "Ryutaro", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Sax", firstName: "Kenneth", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Scanlan", firstName: "Jeff", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Schmer", firstName: "Ryan", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Schneiderat", firstName: "Alexis", dojo: "Maine Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Schroeder", firstName: "Frederick", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Schultz", firstName: "Austin", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Schwartz", firstName: "Megan", dojo: "New England Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sciacca", firstName: "Alex", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Seeley", firstName: "Michal", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Segarra", firstName: "Alexander", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Shamzad", firstName: "Khosravi", dojo: "Hillsboro Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sherman", firstName: "Andrew", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sherman", firstName: "Joseph", dojo: "Seishin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Shockness", firstName: "Angela", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Silkin", firstName: "Andrey", dojo: "D-Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Simon", firstName: "Jorge", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Simon", firstName: "Haley", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Singh", firstName: "Sanjuia", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Singh", firstName: "Sejal", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Soriano", firstName: "Jared", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Soulimen", firstName: "Gedion", dojo: "Reigikai SKIF Las Vegas", rank: "Shodan (1. Dan)" },
  { lastName: "Sowkey", firstName: "Kevin", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Sperry", firstName: "Ryan", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "St. Cyr", firstName: "Brizer", dojo: "Rochester Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Stein", firstName: "Mike", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Stukes", firstName: "Ricardo", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Suarez-Ferguson", firstName: "Lizmery", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Sun", firstName: "Wei", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Suryanarayana", firstName: "Srinivas", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Sverdlow", firstName: "David", dojo: "San Francisco Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Szewczyk", firstName: "Daniel", dojo: "American Tiger Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Taira", firstName: "Troy", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Takahashi", firstName: "Devin", dojo: "S.K.I.F. - Hawaii", rank: "Shodan (1. Dan)" },
  { lastName: "Takei", firstName: "Norihiro", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Takei", firstName: "Kunihiro", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Takemoto", firstName: "Roy", dojo: "S.K.I.F. Hawaii - Susannah Wesley", rank: "Shodan (1. Dan)" },
  { lastName: "Tan", firstName: "Kathleen", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Taniguchi", firstName: "Masako", dojo: "S.K.I.F. - Hawaii - Kona", rank: "Shodan (1. Dan)" },
  { lastName: "Tatseos", firstName: "Alex", dojo: "SKIF of Maine", rank: "Shodan (1. Dan)" },
  { lastName: "Teodore", firstName: "Gafencu", dojo: "Peak Performance Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Thomas", firstName: "Jason", dojo: "Austin Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Thompson", firstName: "Evan", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Thompson", firstName: "Wayne", dojo: "Mt. Vernon Traditional Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Tihou", firstName: "Pierre", dojo: "D-Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Tokloka", firstName: "Abe", dojo: "Affiliated Member", rank: "Shodan (1. Dan)" },
  { lastName: "Torres", firstName: "Joseph", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Shodan (1. Dan)" },
  { lastName: "Tran", firstName: "Kegan", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Shodan (1. Dan)" },
  { lastName: "Tyau-Beam", firstName: "Andrew", dojo: "SKIF-Kaneohe", rank: "Shodan (1. Dan)" },
  { lastName: "Umeno", firstName: "Chane", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Shodan (1. Dan)" },
  { lastName: "Urrea", firstName: "Joaquín", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "Ursua", firstName: "Johan", dojo: "New Roc Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Valdes", firstName: "Richard", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Varags", firstName: "Gabriella", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Varags", firstName: "Kiara", dojo: "Brickell Shotokan Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Varela", firstName: "Maximo", dojo: "Shotokan Karate Academy - ME", rank: "Shodan (1. Dan)" },
  { lastName: "Vaughn", firstName: "Ava", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Vazquez", firstName: "Benjamin", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Ventura", firstName: "Junior", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Ventura", firstName: "Valeria", dojo: "S.K.I.F. Samurai", rank: "Shodan (1. Dan)" },
  { lastName: "Villegas", firstName: "Julio", dojo: "Shotokan-Ryu Karate", rank: "Shodan (1. Dan)" },
  { lastName: "Vissichelli", firstName: "Lisa", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Vissichelli", firstName: "Nicole", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Vo", firstName: "Andrew", dojo: "Keiko Shin Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Vrushab", firstName: "Karthik", dojo: "Hillsboro Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Wajanakunakorn", firstName: "Supranee", dojo: "Satsuma Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Walker", firstName: "Jessica", dojo: "RGV Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Wasiq", firstName: "Rehan", dojo: "Katy/Richmond Karate-dō", rank: "Shodan (1. Dan)" },
  { lastName: "Wasiq", firstName: "Rizwan", dojo: "Katy/Richmond Karate-dō", rank: "Shodan (1. Dan)" },
  { lastName: "Welge", firstName: "Kevin", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Wilkinson", firstName: "Benjamin", dojo: "MSU Karate Club", rank: "Shodan (1. Dan)" },
  { lastName: "Windstead", firstName: "Andrew", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Winsted", firstName: "Andrew", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Wong", firstName: "Daniel", dojo: "Shotokan Karate-Do Center Houston", rank: "Shodan (1. Dan)" },
  { lastName: "Wong", firstName: "Phillip", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Wong", firstName: "Liliana", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Woyak", firstName: "Cody", dojo: "WI Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Wu", firstName: "Paul", dojo: "SKIF-Kaneohe", rank: "Shodan (1. Dan)" },
  { lastName: "Wu", firstName: "Tina", dojo: "Shotokan Karate Juku - CKA", rank: "Shodan (1. Dan)" },
  { lastName: "Yanosik", firstName: "AnnMarie", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Yanosik", firstName: "Michael", dojo: "Long Island Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Yarberry", firstName: "William", dojo: "Texas A & M Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Zabre", firstName: "Erika", dojo: "University of Houston Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Zachary", firstName: "Robert", dojo: "New England Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Zanardo", firstName: "Livio", dojo: "S.K.I.F - Miami", rank: "Shodan (1. Dan)" },
  { lastName: "Zapata", firstName: "Daniella", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Shodan (1. Dan)" },
  { lastName: "Zhao", firstName: "Jun", dojo: "Shockness Shotokan", rank: "Shodan (1. Dan)" },
  { lastName: "Zoard", firstName: "Attila", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "Kona", firstName: "Zuleta Matsiira", dojo: "California Karate Association", rank: "Shodan (1. Dan)" },
  { lastName: "Valeriano", firstName: "Rainen", dojo: "California Karate Association", rank: "Shodan (1. Dan)" },
  { lastName: "Subramony", firstName: "Iyer", dojo: "New England Shotokan Karate-Do", rank: "Shodan (1. Dan)" },
  { lastName: "Kolachina", firstName: "Lasya", dojo: "Doshinkai Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Kolachina", firstName: "Lekhya", dojo: "Doshinkai Dojo", rank: "Shodan (1. Dan)" },
  { lastName: "Smith", firstName: "Kenneth Roy", dojo: "Independent Member", rank: "Shodan (1. Dan)" },
  { lastName: "Kikuchi", firstName: "Ryusei", dojo: "Hillsboro Shotokan Karate Club", rank: "Shodan (1. Dan)" },
  { lastName: "Carpenter", firstName: "Adi", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Carpenter", firstName: "Kai", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },
  { lastName: "Roxburgh-Edstrom", firstName: "Matthew", dojo: "Waikoloa Karate Academy", rank: "Shodan (1. Dan)" },

  // --- NIDAN (2. DAN) ---
  { lastName: "Garcia", firstName: "Alexander", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Aho", firstName: "Luke", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Ali", firstName: "Ameen", dojo: "University of Houston Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Baroek", firstName: "Patricia", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Barruso", firstName: "Joseph", dojo: "S.K.I.F. - Hawaii", rank: "Nidan (2. Dan)" },
  { lastName: "Bell", firstName: "David", dojo: "Affiliated Member", rank: "Nidan (2. Dan)" },
  { lastName: "Beraja", firstName: "Victor", dojo: "Affiliated Member", rank: "Nidan (2. Dan)" },
  { lastName: "Bernabeu", firstName: "Laurent", dojo: "Affiliated Member", rank: "Nidan (2. Dan)" },
  { lastName: "Best", firstName: "Sheldon", dojo: "YMCA Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Braine", firstName: "Charles", dojo: "SKIF of Maine", rank: "Nidan (2. Dan)" },
  { lastName: "Campbell", firstName: "Colin", dojo: "Rochester Shotokan Karate Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Carroll", firstName: "Travis", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Castillo", firstName: "Jay", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Chambers", firstName: "Marvin", dojo: "The Kokujin Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Christian", firstName: "Jeff", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Chun", firstName: "Erin", dojo: "S.K.I.F. - Hawaii", rank: "Nidan (2. Dan)" },
  { lastName: "Co", firstName: "Duong", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Concha", firstName: "Jerry", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "Crader", firstName: "Joan", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Cuizon", firstName: "Dennis", dojo: "Kaumakapili Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Davila", firstName: "Jeffrey", dojo: "S.K.I.F - Miami", rank: "Nidan (2. Dan)" },
  { lastName: "Debeer", firstName: "Richard", dojo: "S.K.I.F. - Hawaii - Kona", rank: "Nidan (2. Dan)" },
  { lastName: "Dent", firstName: "Aric", dojo: "Stevens Point Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Diarra", firstName: "Molissa", dojo: "University of Houston Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Dillard", firstName: "Michael", dojo: "Seishin Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "DiPreta", firstName: "Stephanie", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Doan", firstName: "Steven", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Dowse", firstName: "Harold", dojo: "SKIF of Maine", rank: "Nidan (2. Dan)" },
  { lastName: "Edamura", firstName: "Masahar", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Nidan (2. Dan)" },
  { lastName: "Eder", firstName: "Mark", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Nidan (2. Dan)" },
  { lastName: "Estell", firstName: "Michael", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Farwell", firstName: "Michelle", dojo: "Maine Shotokan Karate Association", rank: "Nidan (2. Dan)" },
  { lastName: "Felipe", firstName: "Diman T.", dojo: "Affiliated Member", rank: "Nidan (2. Dan)" },
  { lastName: "Fuentes", firstName: "Alejandro", dojo: "Keiko Shin Karate Academy", rank: "Nidan (2. Dan)" },
  { lastName: "Fung Quee", firstName: "Ian", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Fung Quee", firstName: "Michael", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Galarza", firstName: "Zion", dojo: "SKIF Windward Oahu Foundation", rank: "Nidan (2. Dan)" },
  { lastName: "Gauthier", firstName: "Keith", dojo: "New England Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Gennosa", firstName: "John", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Gomez-Silva", firstName: "Julio", dojo: "S.K.I.F - Miami", rank: "Nidan (2. Dan)" },
  { lastName: "Grube", firstName: "Mike", dojo: "Rochester Shotokan Karate Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Guiso", firstName: "Mike", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Hernaez", firstName: "Gabe", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Higa", firstName: "Deborah", dojo: "S.K.I.F. - Hawaii", rank: "Nidan (2. Dan)" },
  { lastName: "Higa", firstName: "Justin", dojo: "S.K.I.F. - Hawaii", rank: "Nidan (2. Dan)" },
  { lastName: "Horibe", firstName: "Kenji", dojo: "American Tiger Karate Academy", rank: "Nidan (2. Dan)" },
  { lastName: "Jacobson", firstName: "Ken", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "James", firstName: "Jennifer", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Jeanbart", firstName: "Andre", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "Kaml", firstName: "Clark", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Kaneshiro", firstName: "Ted", dojo: "Kaumakapili Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Keenan", firstName: "Shawn", dojo: "Rochester Shotokan Karate Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Kniska", firstName: "Andrew", dojo: "New England Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Kong", firstName: "Kevin", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Kratofil", firstName: "Steven", dojo: "Seishin Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Krueser", firstName: "Mike", dojo: "YMCA Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Kumagai", firstName: "Russell", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "Kwon", firstName: "Young", dojo: "Austin Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "LaFleur", firstName: "Tim", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Lam", firstName: "Manfred", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "Lavelle", firstName: "Alan", dojo: "Katy/Richmond Karate-dō", rank: "Nidan (2. Dan)" },
  { lastName: "Lee", firstName: "William", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Lev", firstName: "Sharon", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Lim", firstName: "Kelli", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Nidan (2. Dan)" },
  { lastName: "Lorion", firstName: "Anne-Marie", dojo: "S.K.I.F - Miami", rank: "Nidan (2. Dan)" },
  { lastName: "Lucchesi", firstName: "Lisa", dojo: "Hillsboro Shotokan Karate Club", rank: "Nidan (2. Dan)" },
  { lastName: "Luciano", firstName: "Michael", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Lulley", firstName: "Frank", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Maeshiro", firstName: "Madison", dojo: "SKIF-Kaneohe", rank: "Nidan (2. Dan)" },
  { lastName: "Manash", firstName: "Ninos", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "McEvoy", firstName: "Ellen", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Meekunnasombat", firstName: "Phongsan", dojo: "WI Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Mendelsohn", firstName: "Shalie", dojo: "Independent Member", rank: "Nidan (2. Dan)" },
  { lastName: "Milan", firstName: "Jorge", dojo: "Brickell Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Mohyla", firstName: "Michelle", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Montalvo", firstName: "Yvonne", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Mooar", firstName: "Robert", dojo: "Maine Shotokan Karate Association", rank: "Nidan (2. Dan)" },
  { lastName: "Moody", firstName: "David", dojo: "Rochester Shotokan Karate Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Nakamoto", firstName: "Kevin", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Nidan (2. Dan)" },
  { lastName: "Natanasabapathy", firstName: "Gautham", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Neglia", firstName: "Joseph", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Nene", firstName: "Clifford", dojo: "S.K.I.F. - Hawaii", rank: "Nidan (2. Dan)" },
  { lastName: "Ors", firstName: "Fernando", dojo: "S.K.I.F - Miami", rank: "Nidan (2. Dan)" },
  { lastName: "Ortiz", firstName: "Maria", dojo: "Rochester Shotokan Karate Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Panayotov", firstName: "Valentin", dojo: "Austin Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Parker", firstName: "Claire", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Patterson", firstName: "Kellie", dojo: "Long Island Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Pettaway", firstName: "Keisha", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Nidan (2. Dan)" },
  { lastName: "Pettaway", firstName: "Tuan", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Nidan (2. Dan)" },
  { lastName: "Plume", firstName: "Daniel", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Prasobsri", firstName: "Krissana", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Prendergast", firstName: "Rebecca", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Nidan (2. Dan)" },
  { lastName: "Price", firstName: "Charles", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Real Bravo", firstName: "Fabiana", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Robinson", firstName: "Ed", dojo: "Shockness Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Rosado Jr", firstName: "Rudolph", dojo: "New Roc Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Rosas", firstName: "Peter", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Ruiz Jr", firstName: "Benjamin", dojo: "S.K.I.F. - New Jersey", rank: "Nidan (2. Dan)" },
  { lastName: "Sanford", firstName: "Rhina", dojo: "Satsuma Dojo", rank: "Nidan (2. Dan)" },
  { lastName: "Sato", firstName: "Malia", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Nidan (2. Dan)" },
  { lastName: "Scarzello", firstName: "Arthur", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Shimana", firstName: "Christopher", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Nidan (2. Dan)" },
  { lastName: "Singh", firstName: "Dalip", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Skordos", firstName: "Ann Marie", dojo: "S.K.I.F. - New York", rank: "Nidan (2. Dan)" },
  { lastName: "Slater", firstName: "Jeremy", dojo: "University of Houston Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Solis", firstName: "Vanessa", dojo: "New Roc Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Stalnaker", firstName: "Jack", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Stepanek", firstName: "Martin", dojo: "S.K.I.F. - Hawaii - Kona", rank: "Nidan (2. Dan)" },
  { lastName: "Stukes", firstName: "Ricky", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Subramanian", firstName: "Arjun", dojo: "Hillsboro Shotokan Karate Club", rank: "Nidan (2. Dan)" },
  { lastName: "Svidzinsky", firstName: "Anatoly", dojo: "Texas A & M Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Swain", firstName: "Steve", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Szewczyk", firstName: "Christopher", dojo: "American Tiger Karate Academy", rank: "Nidan (2. Dan)" },
  { lastName: "Tantingco", firstName: "Norman", dojo: "Shotokan Karate Academy - ME", rank: "Nidan (2. Dan)" },
  { lastName: "Tokioka", firstName: "Abe", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Nidan (2. Dan)" },
  { lastName: "Tolentino", firstName: "Joseph", dojo: "Reigikai SKIF Las Vegas", rank: "Nidan (2. Dan)" },
  { lastName: "Tolentino", firstName: "Joshua", dojo: "Reigikai SKIF Las Vegas", rank: "Nidan (2. Dan)" },
  { lastName: "Tominaga", firstName: "Joshua", dojo: "Shotokan Karate-Do Club", rank: "Nidan (2. Dan)" },
  { lastName: "Tshibamba", firstName: "Daniel", dojo: "Shotokan Karate Shobukan", rank: "Nidan (2. Dan)" },
  { lastName: "Vargas", firstName: "James", dojo: "New Roc Shotokan Karate", rank: "Nidan (2. Dan)" },
  { lastName: "Villanueva", firstName: "Jeremy", dojo: "Mt. Vernon Traditional Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Vo", firstName: "Derick", dojo: "Keiko Shin Karate Academy", rank: "Nidan (2. Dan)" },
  { lastName: "Vukasinovic", firstName: "Dragon", dojo: "S.K.I.F. - New York", rank: "Nidan (2. Dan)" },
  { lastName: "Wainwright", firstName: "Alex", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Walker", firstName: "Jeremiah", dojo: "RGV Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Weelborg", firstName: "Brad", dojo: "MSU Karate Club", rank: "Nidan (2. Dan)" },
  { lastName: "William", firstName: "Gilbert", dojo: "Independent Member", rank: "Nidan (2. Dan)" },
  { lastName: "Willner", firstName: "Stewart", dojo: "Shotokan Karate Juku - CKA", rank: "Nidan (2. Dan)" },
  { lastName: "Wilson", firstName: "Maribel", dojo: "RGV Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Yasuhiro", firstName: "Louis", dojo: "San Francisco Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Zhang", firstName: "Xiwen", dojo: "Texas A & M Shotokan", rank: "Nidan (2. Dan)" },
  { lastName: "Zoltan", firstName: "Attilla", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Zuniga", firstName: "Daniel", dojo: "Peak Performance Shotokan Karate-Do", rank: "Nidan (2. Dan)" },
  { lastName: "Guzman Diaz", firstName: "Juan Rafeal", dojo: "Martial Arts University", rank: "Nidan (2. Dan)" },
  { lastName: "Sardesai", firstName: "Swati", dojo: "Shotokan Karate-Do Center Houston", rank: "Nidan (2. Dan)" },
  { lastName: "Shimazu", firstName: "Jessica", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Nidan (2. Dan)" },
  { lastName: "Toth", firstName: "Attila", dojo: "Independent Member", rank: "Nidan (2. Dan)" },
  { lastName: "Robinson", firstName: "Sean", dojo: "Independent Member", rank: "Nidan (2. Dan)" },
  { lastName: "Ramos", firstName: "Jesse", dojo: "JCCH", rank: "Nidan (2. Dan)" },

  // --- SANDAN (3. DAN) ---
  { lastName: "Babiyets", firstName: "Voldoymyr", dojo: "San Francisco Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Baksmaty", firstName: "Leslie", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Balakrishnan", firstName: "Nathan", dojo: "Golden Tiger Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Barber", firstName: "Cole", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Barker", firstName: "Bruce C.", dojo: "SKIF of Maine", rank: "Sandan (3. Dan)" },
  { lastName: "Barnabei", firstName: "Henry", dojo: "Shotokan Karate-Do Florida “SKF”", rank: "Sandan (3. Dan)" },
  { lastName: "Bishop", firstName: "Raymond", dojo: "Rochester Shotokan Karate Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Blindauer", firstName: "Tim", dojo: "Shotokan Karate Club Madison", rank: "Sandan (3. Dan)" },
  { lastName: "Bouchie", firstName: "Vasna", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Briguene", firstName: "Ahcene", dojo: "U.S.K.A.", rank: "Sandan (3. Dan)" },
  { lastName: "Canny", firstName: "John", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Chakoumakos", firstName: "Alison", dojo: "Rocky Mtn Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Clinkscales", firstName: "Daniel", dojo: "Danha Kai Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Connors", firstName: "Bridget", dojo: "Shotokan Karate Academy - ME", rank: "Sandan (3. Dan)" },
  { lastName: "Davis", firstName: "Bruce", dojo: "Shotokan Karate Club Madison", rank: "Sandan (3. Dan)" },
  { lastName: "De Los Reyes", firstName: "Ramilo E", dojo: "Shotokan Karate Juku - CKA", rank: "Sandan (3. Dan)" },
  { lastName: "DiCanio", firstName: "Gerard", dojo: "Long Island Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Espinosa", firstName: "Fernando", dojo: "WI Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Ferrando", firstName: "Stephen", dojo: "Long Island Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Ferrario", firstName: "Paola", dojo: "New England Shotokan Karate-Do", rank: "Sandan (3. Dan)" },
  { lastName: "Formica", firstName: "Joseph", dojo: "Austin Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Gale", firstName: "Paul", dojo: "Shotokan Karate Juku - CKA", rank: "Sandan (3. Dan)" },
  { lastName: "Grozdanov", firstName: "Petar", dojo: "Mt. Vernon Traditional Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Grube", firstName: "Henrich", dojo: "Maine Shotokan Karate Association", rank: "Sandan (3. Dan)" },
  { lastName: "Hayaghaibi-Fung", firstName: "Shireen", dojo: "Doshinkai Dojo SKIF Cincinnati", rank: "Sandan (3. Dan)" },
  { lastName: "Hilario", firstName: "Rigatcho", dojo: "Shotokan Karate Club Madison", rank: "Sandan (3. Dan)" },
  { lastName: "Hiyoshi", firstName: "Ryuji", dojo: "Mt. Vernon Traditional Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Johnson", firstName: "Wesley", dojo: "Peak Performance Shotokan Karate-Do", rank: "Sandan (3. Dan)" },
  { lastName: "Jorden", firstName: "Corpuz", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Sandan (3. Dan)" },
  { lastName: "Kakuda", firstName: "Leslie", dojo: "S.K.I.F. Hawaii - Susannah Wesley Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Kaneko", firstName: "Carly", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Sandan (3. Dan)" },
  { lastName: "Kreuter", firstName: "Urs", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Lentz", firstName: "Colin", dojo: "Rochester Shotokan Karate Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Lin", firstName: "Kathy", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Lintula", firstName: "Mark", dojo: "Peak Performance Shotokan Karate-Do", rank: "Sandan (3. Dan)" },
  { lastName: "Luquin", firstName: "Miguel", dojo: "Shotokan Karate Juku - CKA", rank: "Sandan (3. Dan)" },
  { lastName: "Masami Okano", firstName: "Stanley", dojo: "S.K.I.F. - Hawaii", rank: "Sandan (3. Dan)" },
  { lastName: "McGibbon", firstName: "Richard R.", dojo: "SKIF of Maine – Millinocket", rank: "Sandan (3. Dan)" },
  { lastName: "Meier", firstName: "Michael", dojo: "American Tiger Karate Academy", rank: "Sandan (3. Dan)" },
  { lastName: "Moats", firstName: "Shaun", dojo: "Independent Member", rank: "Sandan (3. Dan)" },
  { lastName: "Mondello", firstName: "Michael", dojo: "Long Island Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Monroe", firstName: "Norman", dojo: "Austin Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Morita", firstName: "Ivan", dojo: "S.K.I.F. - Hawaii", rank: "Sandan (3. Dan)" },
  { lastName: "Ngoon", firstName: "Patrick", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Porter", firstName: "Lorri", dojo: "Independent Member", rank: "Sandan (3. Dan)" },
  { lastName: "Pray", firstName: "Thomas", dojo: "New England Shotokan Karate-Do", rank: "Sandan (3. Dan)" },
  { lastName: "Pusateri", firstName: "Patricia", dojo: "American Tiger Karate Academy", rank: "Sandan (3. Dan)" },
  { lastName: "Py", firstName: "Cyril", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Ramsay", firstName: "Erik", dojo: "Rochester Shotokan Karate Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Rexha", firstName: "Vebhi", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Rios", firstName: "Juan", dojo: "Mt. Vernon Traditional Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Rosado Sr", firstName: "Rudolph", dojo: "New Roc Shotokan Karate", rank: "Sandan (3. Dan)" },
  { lastName: "Salibi", firstName: "Kamal", dojo: "Kauai Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Sanehira", firstName: "Todd", dojo: "S.K.I.F. Hawaii - Susannah Wesley Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Sasano", firstName: "Clifford", dojo: "Kaumakapili Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Shirazi-Fard", firstName: "Yasaman", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Slausen", firstName: "Kevin", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Stenhouse", firstName: "John B.", dojo: "CSUN Karate Club", rank: "Sandan (3. Dan)" },
  { lastName: "Takahashi", firstName: "Ross", dojo: "SKIF-Kaneohe", rank: "Sandan (3. Dan)" },
  { lastName: "Teoh", firstName: "H.B.", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Thom", firstName: "Rodwell", dojo: "University of Houston Shotokan", rank: "Sandan (3. Dan)" },
  { lastName: "Tolentino", firstName: "Ronald", dojo: "Reigikai SKIF Las Vegas", rank: "Sandan (3. Dan)" },
  { lastName: "Uray", firstName: "Ivan", dojo: "Shotokan Karate-Do Center Houston", rank: "Sandan (3. Dan)" },
  { lastName: "Vapirev", firstName: "Alexander", dojo: "Rochester Shotokan Karate Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Wajanakunakorn", firstName: "Sekson", dojo: "Satsuma Dojo", rank: "Sandan (3. Dan)" },
  { lastName: "Willie", firstName: "Mark", dojo: "MSU Karate Club", rank: "Sandan (3. Dan)" },
  { lastName: "Yee", firstName: "Gary", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Sandan (3. Dan)" },
  { lastName: "Blackwell", firstName: "Amy", dojo: "Tora Dento Martial Arts", rank: "Sandan (3. Dan)" },
  { lastName: "Guzman", firstName: "Oscar", dojo: "Independent Member", rank: "Sandan (3. Dan)" },
  { lastName: "Meyer", firstName: "James", dojo: "MSU Karate Club", rank: "Sandan (3. Dan)" },
  { lastName: "Rodriguez", firstName: "Carlos", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Sandan (3. Dan)" },

  // --- YONDAN (4. DAN) ---
  { lastName: "Aponte", firstName: "Ty", dojo: "Shotokan Karate Juku - CKA", rank: "Yondan (4. Dan)" },
  { lastName: "Bashirov", firstName: "Novruz", dojo: "D-Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Brathwaite", firstName: "Wade", dojo: "Mt. Vernon Traditional Shotokan", rank: "Yondan (4. Dan)" },
  { lastName: "Chibundu", firstName: "Emmanuel", dojo: "Shotokan Karate-Do Center Houston", rank: "Yondan (4. Dan)" },
  { lastName: "Correia", firstName: "Jonas", dojo: "Samurai Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Daniel", firstName: "Mathieu", dojo: "Peak Performance Shotokan Karate-Do", rank: "Yondan (4. Dan)" },
  { lastName: "De Asis", firstName: "Eddie", dojo: "S.K.I.F. Hawaii - Susannah Wesley", rank: "Yondan (4. Dan)" },
  { lastName: "Dionne", firstName: "Richard", dojo: "Hillsboro Shotokan Karate Club", rank: "Yondan (4. Dan)" },
  { lastName: "Edamura", firstName: "Masa", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Yondan (4. Dan)" },
  { lastName: "Foord", firstName: "Erin", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Fung", firstName: "Bennett", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Yondan (4. Dan)" },
  { lastName: "Higa", firstName: "Melvin", dojo: "SKIF Windward Oahu Foundation", rank: "Yondan (4. Dan)" },
  { lastName: "Jowkar", firstName: "Rod", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Kaneko", firstName: "Michael", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Yondan (4. Dan)" },
  { lastName: "Kikuchi Lavallete", firstName: "Yukiko", dojo: "Doshinkai Dojo SKIF Cincinnati", rank: "Yondan (4. Dan)" },
  { lastName: "Lam", firstName: "Michael", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Marotta", firstName: "Edward", dojo: "New England Shotokan Karate-Do", rank: "Yondan (4. Dan)" },
  { lastName: "Morimoto", firstName: "Mayumi", dojo: "Shockness Shotokan", rank: "Yondan (4. Dan)" },
  { lastName: "Neves", firstName: "Ricardo", dojo: "S.K.I.F. - New York", rank: "Yondan (4. Dan)" },
  { lastName: "Nobida", firstName: "Martin", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Parameswaran", firstName: "Gopakumar", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Patail", firstName: "Saad", dojo: "Shotokan Karate Juku - CKA", rank: "Yondan (4. Dan)" },
  { lastName: "Patail", firstName: "Stephanie", dojo: "Shotokan Karate Juku - CKA", rank: "Yondan (4. Dan)" },
  { lastName: "Pius", firstName: "Thomas", dojo: "NE Shotokan", rank: "Yondan (4. Dan)" },
  { lastName: "Raymond", firstName: "Eric", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Razavizadeh", firstName: "Moe", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Richardson", firstName: "Mark", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Rodriguez", firstName: "Peter", dojo: "ShoShin Karate", rank: "Yondan (4. Dan)" },
  { lastName: "Sanchez", firstName: "Roberto", dojo: "Independent Member", rank: "Yondan (4. Dan)" },
  { lastName: "Skordos", firstName: "Angelo", dojo: "S.K.I.F. - New York", rank: "Yondan (4. Dan)" },
  { lastName: "Sullivan", firstName: "Greg", dojo: "Peak Performance Shotokan Karate-Do", rank: "Yondan (4. Dan)" },
  { lastName: "Swinehart", firstName: "Charles", dojo: "Satsuma Dojo", rank: "Yondan (4. Dan)" },
  { lastName: "Tamayose", firstName: "Kevin", dojo: "Chozen-Ji Karate Dojo Hawaii", rank: "Yondan (4. Dan)" },
  { lastName: "Tavakol", firstName: "Siamak", dojo: "Katy/Richmond Karate-dō", rank: "Yondan (4. Dan)" },
  { lastName: "Tretyak", firstName: "Yuriy", dojo: "Independent Member", rank: "Yondan (4. Dan)" },
  { lastName: "Turner", firstName: "Lisa", dojo: "Maine Shotokan Karate Association", rank: "Yondan (4. Dan)" },
  { lastName: "Valentin", firstName: "Charles", dojo: "Shotokan-Ryu Karate", rank: "Yondan (4. Dan)" },
  { lastName: "Vargas", firstName: "Jorge", dojo: "S.K.I.F - Miami", rank: "Yondan (4. Dan)" },
  { lastName: "Villanueva", firstName: "Jerry", dojo: "SKIF Windward Oahu Foundation", rank: "Yondan (4. Dan)" },
  { lastName: "Wilkinson", firstName: "Tom", dojo: "New England Shotokan Karate-Do", rank: "Yondan (4. Dan)" },
  { lastName: "Wong", firstName: "Steven", dojo: "S.K.I.F. Hawaii - Susannah Wesley", rank: "Yondan (4. Dan)" },
  { lastName: "Zayed", firstName: "Mike", dojo: "Shotokan Karate-Do Center Houston", rank: "Yondan (4. Dan)" },
  { lastName: "Zegarra", firstName: "Paul", dojo: "Mt. Vernon Traditional Shotokan", rank: "Yondan (4. Dan)" },

  // --- GODAN (5. DAN) ---
  { lastName: "Amarjargal", firstName: "Enkhbold", dojo: "Satsuma Dojo", rank: "Godan (5. Dan)" },
  { lastName: "Baston", firstName: "Milton", dojo: "Maine Shotokan Karate Association", rank: "Godan (5. Dan)" },
  { lastName: "Carew", firstName: "Roy", dojo: "Shotokan Karate Juku - CKA", rank: "Godan (5. Dan)" },
  { lastName: "Chen", firstName: "Lisa", dojo: "Shotokan Karate-Do Center Houston", rank: "Godan (5. Dan)" },
  { lastName: "Dumothier", firstName: "Stephan", dojo: "Shotokan Karate-Do Center Houston", rank: "Godan (5. Dan)" },
  { lastName: "Goshadze", firstName: "George", dojo: "S.K.I.F. - New York", rank: "Godan (5. Dan)" },
  { lastName: "Jones", firstName: "Wayne", dojo: "Independent Member", rank: "Godan (5. Dan)" },
  { lastName: "Karpovsky", firstName: "Penny", dojo: "Shotokan Karate Juku - CKA", rank: "Godan (5. Dan)" },
  { lastName: "Lee", firstName: "Charles", dojo: "SKIF Georgia", rank: "Godan (5. Dan)" },
  { lastName: "Lewis", firstName: "Dean", dojo: "Satsuma Dojo", rank: "Godan (5. Dan)" },
  { lastName: "Macolino", firstName: "Charles", dojo: "Long Island Shotokan", rank: "Godan (5. Dan)" },
  { lastName: "Maeshiro", firstName: "Robert", dojo: "SKIF-Kaneohe", rank: "Godan (5. Dan)" },
  { lastName: "Morton", firstName: "Clay", dojo: "Independent Member", rank: "Godan (5. Dan)" },
  { lastName: "Moule", firstName: "Pierre", dojo: "World Sports Fitness", rank: "Godan (5. Dan)" },
  { lastName: "Nichiporuk", firstName: "Theresa", dojo: "Mt. Vernon Traditional Shotokan", rank: "Godan (5. Dan)" },
  { lastName: "Nishikawa", firstName: "Shinobu", dojo: "S.K.I.F. - Hawaii", rank: "Godan (5. Dan)" },
  { lastName: "Nouchi", firstName: "Robert", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Godan (5. Dan)" },
  { lastName: "Odani", firstName: "Norman", dojo: "S.K.I.F. - Hawaii", rank: "Godan (5. Dan)" },
  { lastName: "Radhakrishman", firstName: "Mithun", dojo: "Satsuma Dojo", rank: "Godan (5. Dan)" },
  { lastName: "Ramnarine", firstName: "Sean", dojo: "S.K.I.F. Samurai", rank: "Godan (5. Dan)" },
  { lastName: "Sato", firstName: "Warren", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Godan (5. Dan)" },
  { lastName: "Slauson", firstName: "Kevin", dojo: "Satsuma Dojo", rank: "Godan (5. Dan)" },
  { lastName: "Vaughn", firstName: "Nelson", dojo: "Waikoloa Karate Academy", rank: "Godan (5. Dan)" },
  { lastName: "Walker", firstName: "Paul", dojo: "Seishin Shotokan", rank: "Godan (5. Dan)" },
  { lastName: "Yasuhiro", firstName: "Masashi", dojo: "San Francisco Shotokan", rank: "Godan (5. Dan)" },
  { lastName: "Gasparakis", firstName: "Joseph", dojo: "Hillsboro Shotokan Karate Club", rank: "Godan (5. Dan)" },
  { lastName: "Urrea G.", firstName: "Joaquin S.", dojo: "Independent Member", rank: "Godan (5. Dan)" },

  // --- ROKUDAN (6. DAN) ---
  { lastName: "Arsanjani", firstName: "Ali", dojo: "Shotokan Karate Keiko Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Baker", firstName: "Charles", dojo: "Nakamichi Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Burleson", firstName: "Glenn", dojo: "Peak Performance Shotokan Karate-Do", rank: "Rokudan (6. Dan)" },
  { lastName: "Crimmins", firstName: "Lynda", dojo: "Peak Performance Shotokan Karate-Do", rank: "Rokudan (6. Dan)" },
  { lastName: "Fung", firstName: "Ruben", dojo: "Doshinkai Dojo, Shotokan Karate-Do Center Houston", rank: "Rokudan (6. Dan)" },
  { lastName: "Gonzalez", firstName: "Vincente", dojo: "SKI Florida", rank: "Rokudan (6. Dan)" },
  { lastName: "Johnson", firstName: "Chris", dojo: "Peak Performance Shotokan Karate-Do", rank: "Rokudan (6. Dan)" },
  { lastName: "Lucchesi", firstName: "Steve", dojo: "Satsuma Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Mansyur", firstName: "Deddy", dojo: "University of Houston Shotokan", rank: "Rokudan (6. Dan)" },
  { lastName: "Manuel", firstName: "Paul", dojo: "Northern Bedford Martial Arts", rank: "Rokudan (6. Dan)" },
  { lastName: "Nguyen", firstName: "Bac", dojo: "Satsuma Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Ono", firstName: "Stanley", dojo: "S.K.I.F. - Hawaii", rank: "Rokudan (6. Dan)" },
  { lastName: "Rodriguez", firstName: "Roddy", dojo: "Satsuma Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Sakai", firstName: "Stuart", dojo: "Satsuma Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Seigo Nakano", firstName: "Seigo Nakano", dojo: "D-Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Smith", firstName: "Eugene", dojo: "Peak Performance Shotokan Karate-Do", rank: "Rokudan (6. Dan)" },
  { lastName: "Warren", firstName: "Steven", dojo: "Rochester Shotokan Karate Dojo", rank: "Rokudan (6. Dan)" },
  { lastName: "Zoraster", firstName: "Richard", dojo: "SKIF Windward Oahu Foundation", rank: "Rokudan (6. Dan)" },

  // --- NANADAN (7. DAN) ---
  { lastName: "Cook", firstName: "Michael", dojo: "Maine Shotokan Karate Association", rank: "Nanadan (7. Dan)" },
  { lastName: "Daylami", firstName: "Kayarash", dojo: "Shotokan Karate-Do Center Houston", rank: "Nanadan (7. Dan)" },
  { lastName: "Nagel", firstName: "Manfred", dojo: "SKIF Windward Oahu Foundation", rank: "Nanadan (7. Dan)" },
  { lastName: "Nishimura", firstName: "Robert", dojo: "Kaumakapili Dojo", rank: "Nanadan (7. Dan)" },
  { lastName: "Shea", firstName: "James", dojo: "New England Shotokan Karate-Do", rank: "Nanadan (7. Dan)" },
  { lastName: "Taira", firstName: "Gilbert", dojo: "S.K.I.F. - Hawaii - Kona", rank: "Nanadan (7. Dan)" },
  { lastName: "Danos", firstName: "Paul", dojo: "S.K.I.F. Samurai", rank: "Nanadan (7. Dan)" },

  // --- HACHIDAN (8. DAN) ---
  { lastName: "Awa", firstName: "Ronald", dojo: "S.K.I.F. - Hawaii - Iwilei", rank: "Hachidan (8. Dan)" },
  { lastName: "Castellano", firstName: "Jay", dojo: "Satsuma Dojo", rank: "Hachidan (8. Dan)" },
  { lastName: "Fong", firstName: "Francis", dojo: "S.K.I.F. Hawaii - Salt Lake", rank: "Hachidan (8. Dan)" },
  { lastName: "Fujishima", firstName: "Hiroyasu", dojo: "Shotokan Karate Juku - CKA", rank: "Hachidan (8. Dan)" },
  { lastName: "Kiyuna", firstName: "Edward", dojo: "S.K.I.F. Hawaii - Susannah Wesley Dojo", rank: "Hachidan (8. Dan)" },
  { lastName: "Stoddard", firstName: "Glenn", dojo: "Wisconsin Shotokan", rank: "Hachidan (8. Dan)" },

  // --- KUDAN (9. DAN) ---
  { lastName: "Takemori", firstName: "Victor", dojo: "S.K.I.F. Hawaii - Pearl City", rank: "Kudan (9. Dan)" },
];

export default function BlackBeltRegistry() {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedDan, setSelectedDan] = useState("All");

  const hasStartedSearch = searchQuery.length > 0 || selectedDan !== "All";

  const filteredRegistry = registryData.filter(member => {
    const fullName = `${member.firstName} ${member.lastName}`.toLowerCase();
    const matchesName = fullName.includes(searchQuery.toLowerCase());
    const matchesDan = selectedDan === "All" || member.rank === selectedDan;
    return matchesName && matchesDan;
  });

  return (
    <main className="min-h-screen bg-[#F5F5F5] text-neutral-900 selection:bg-red-600 selection:text-white pt-28 md:pt-48 pb-20 px-6">
      <div className="container mx-auto max-w-6xl">
        
        {/* --- HEADER --- */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="mb-16 border-l-4 border-red-600 pl-6 max-w-4xl"
        >
          <h2 className="text-red-600 font-bold uppercase tracking-[0.2em] text-sm mb-2">Member Verification</h2>
          <h1 className="text-5xl md:text-7xl font-black uppercase tracking-tighter leading-none text-neutral-900">
            Black Belt <span className="text-neutral-400">Registry</span>
          </h1>
          <p className="text-neutral-600 mt-6 text-lg max-w-2xl leading-relaxed">
            Verify official SKIF-USA technical grades and dojo affiliations through the centralized registry.
          </p>
        </motion.div>

        {/* --- SEARCH & FILTER SECTION --- */}
        <div className="flex flex-col md:flex-row gap-4 mb-12">
          <div className="relative flex-1 group">
            <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-neutral-400 group-focus-within:text-red-600 transition-colors" size={20} />
            <input 
              type="text" 
              placeholder="SEARCH BY NAME..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-white border border-neutral-200 rounded-2xl py-5 pl-14 pr-6 focus:outline-none focus:border-red-600 focus:shadow-md transition-all font-bold uppercase tracking-widest text-sm placeholder:text-neutral-400 text-neutral-900"
            />
          </div>
          
          <div className="relative w-full md:w-80">
            <Filter className="absolute left-5 top-1/2 -translate-y-1/2 text-neutral-400 pointer-events-none" size={18} />
            <select 
              value={selectedDan}
              onChange={(e) => setSelectedDan(e.target.value)}
              className="w-full h-full bg-white border border-neutral-200 rounded-2xl py-5 pl-14 pr-10 focus:outline-none focus:border-red-600 focus:shadow-md transition-all font-black uppercase tracking-widest text-sm appearance-none cursor-pointer text-neutral-900"
            >
              <option value="All">ALL DAN GRADES</option>
              {danGrades.map(grade => (
                <option key={grade} value={grade}>{grade.toUpperCase()}</option>
              ))}
            </select>
          </div>
        </div>

        {/* --- RESULTS AREA --- */}
        <div className="min-h-[400px]">
          <AnimatePresence mode="wait">
            {!hasStartedSearch ? (
              <motion.div 
                key="prompt"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="py-32 text-center border-2 border-dashed border-neutral-300 bg-white rounded-[3.5rem] flex flex-col items-center justify-center gap-6"
              >
                <div className="w-16 h-16 bg-neutral-100 rounded-full flex items-center justify-center text-neutral-400">
                    <ShieldCheck size={32} />
                </div>
                <p className="text-neutral-500 uppercase tracking-[0.4em] font-black text-sm">
                  Enter a name or select a rank to begin verification
                </p>
              </motion.div>
            ) : filteredRegistry.length > 0 ? (
              <motion.div 
                key="results"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="overflow-x-auto bg-white border border-neutral-200 rounded-[2.5rem] shadow-xl"
              >
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b border-neutral-200 bg-neutral-50">
                      <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500">Last Name</th>
                      <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500">First Name</th>
                      <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500">Dojo Name</th>
                      <th className="px-8 py-6 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500 text-right">Technical Rank</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredRegistry.map((member, idx) => (
                      <tr key={idx} className="group hover:bg-neutral-50 transition-colors border-b border-neutral-100 last:border-0">
                        <td className="px-8 py-6 font-black uppercase tracking-tight text-neutral-900 group-hover:text-red-600 transition-colors">{member.lastName}</td>
                        <td className="px-8 py-6 font-bold uppercase text-sm text-neutral-600">{member.firstName}</td>
                        <td className="px-8 py-6">
                           <div className="flex items-center gap-2 text-neutral-500 text-xs font-medium uppercase tracking-wide">
                             <MapPin size={14} className="text-red-600" /> {member.dojo}
                           </div>
                        </td>
                        <td className="px-8 py-6 text-right">
                          <div className="inline-flex flex-col items-end border-l-2 border-red-600 pl-4 py-1">
                            <span className="text-neutral-900 font-black uppercase text-xs tracking-tighter leading-none mb-1 group-hover:text-red-600 transition-colors">
                              {member.rank.split(' ')[0]}
                            </span>
                            <span className="text-neutral-400 font-mono text-[9px] font-bold uppercase tracking-widest">
                              {member.rank.split(' ')[1]} {member.rank.split(' ')[2]}
                            </span>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </motion.div>
            ) : (
              <motion.div 
                key="empty"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="py-40 text-center border-2 border-dashed border-neutral-300 bg-white rounded-[3.5rem]"
              >
                <p className="text-neutral-500 uppercase tracking-[0.4em] font-black text-sm">No registered members found.</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        <div className="mt-32 text-center border-t border-neutral-200 pt-16">
          <p className="text-neutral-400 uppercase tracking-[0.5em] text-[10px] font-mono">
            One Style • One Spirit • One Federation
          </p>
        </div>

      </div>
    </main>
  );
}